package UltimateBravery.src.main.FoodUtility

class Food {
  val food: List[String] = List(
    "Plate of Jerk Poultry",
    "Plate of Truffle Steak",
    "Steak with Winterberry Sauce",
    "Spicy Marinated Mushroom",
    "Plate of Orrian Steak Frittes",
    "Plate of Fire Flank Steak",
    "Bowl of Sweet and Spicy Butternut Squash Soup",
    "Plate of Spicy Moa Wings",
    "Bowl of Passion Fruit Tapioca Pudding",
    "Bowl of Curry Pumpkin Soup",
    "Bowl of Fancy Potato and Leek Soup",
    "Bowl of Curry Butternut Squash Soup",
    "Plate of Spicy Herbed Chicken",
    "Bowl of Truffle Ravioli",
    "Plate of Frostgorge Clams",
    "Bowl of Tropical Mousse",
    "Bowl of Chocolate Tapioca Pudding",
    "Bowl of Refugee's Beet Soup",
    "Flatbread",
    "Mushroom Loaf",
    "Loaf of Omnomberry Bread",
    "Bowl of Zesty Turnip Soup",
    "Soul Pastry",
    "Loaf of Candy Cactus Cornbread",
    "Bowl of Nopalitos Sauté",
    "Plate of Eggs Benedict",
    "Bowl of Green Chile Ice Cream",
    "Bowl of Carne Khan Chili",
    "Bowl of Firebreather Chili",
    "Bowl of Truffle Risotto",
    "Bowl of Orrian Truffle Soup",
    "Plate of Beef Rendang",
    "Bowl of Prickly Pear Tapioca Pudding",
    "Prickly Pear Stuffed Nopal",
    "Bowl of Sweet and Spicy Beans",
    "Koi Cake",
    "Rare Veggie Pizza",
    "Bowl of Garlic Kale Sautee",
    "Red-Lentil Saobosa",
    "Prickly Pear Pie",
    "Bowl of Cactus Fruit Salad",
    "Bowl of Elon Red",
    "Bowl of Fire Meat Chili",
    "Fishy Rice Bowl",
    "Chocolate Omnomberry Cake",
    "Fancy Truffle Burger",
    "Bowl of Kimchi Tofu Stew",
    "Meaty Asparagus Skewer",
    "Meaty Rice Bowl",
    "Plate of Kimchi Pancakes",
    "Bowl of Fire Veggie Chili",
    "Bowl of Prickly Pear Sorbet",
    "Winterberry Sorbet",
    "Plate of Roasted Cactus",
    "Delicious Rice Ball",
    "Spicy Chocolate Cookie",
    "Omnomberry Cookie",
    "Bowl of Tropical Fruit Salad",
    "Bowl of Poultry Satay",
    "Bowl of Saffron-scented Poultry Soup",
    "Kralkachocolate Bar",
    "Bowl of Saffron-Mango Ice Cream",
    "Redfish Sushi",
    "Bowl of Fish Stew",
    "Bowl of Echovald Hotpot",
    "Bowl of Jade Sea Bounty",
    "Flight of Sushi",
    "Plate of Crispy Fish Pancakes",
    "Plate of Imperial Palace Special",
    "Plate of Island Pudding",
    "Dragonfly Cupcake",
    "Omnomberry Tart",
    "Chocolate Omnomberry Cream",
    "Cup of Lotus Fries",
    "Spicy Pumpkin Cookie",
    "Omnomberry Bar",
    "Peppermint Omnomberry Bar",
    "Dragon's Revelry Starcake",
    "Tray of Decade Desserts",
    "Fried Oysters",
    "Fried Oyster Sandwich",
    "Oysters with Cocktail Sauce",
    "Bowl of Lemongrass Mussel Pasta",
    "Bowl of Mussel Soup",
    "Plate of Mussels Gnashblade",
    "Oysters with Spicy Sauce",
    "Oysters Gnashblade",
    "Oysters with Zesty Sauce",
    "Oysters with Pesto Sauce",
    "Bowl of Curry Mussel Soup",
    "Plate of Peppercorn-Spiced Coq Au Vin",
    "Mists-Infused Peppercorn-Crusted Sous-Vide Steak",
    "Peppercorn-Crusted Sous-Vide Steak",
    "Plate of Peppered Clear Truffle Ravioli",
    "Plate of Peppercorn-Spiced Beef Carpaccio",
    "Plate of Peppercorn-Spiced Poultry Aspic",
    "Peppercorn-Spiced Eggs Benedict",
    "Spiced Pepper Creme Brulee",
    "Spiced Peppercorn Cheesecake",
    "Peppered Cured Meat Flatbread",
    "Peppercorn and Veggie Flatbread",
    "Bowl of Spiced Fruit Salad",
    "Spherified Peppercorn-Spiced Oyster Soup",
    "Mists-Infused Spherified Peppercorn-Spiced Oyster Soup",
    "Loaf of Saffron Bread",
    "Bowl of Lemongrass Poultry Soup",
    "Quiche of Darkness",
    "Sweet Bean Bun",
    "Plate of Clove-Spiced Coq Au Vin",
    "Mushroom Clove Sous-Vide Steak",
    "Plate of Clove-Spiced Clear Truffle Ravioli",
    "Plate of Clove-Spiced Beef Carpaccio",
    "Plate of Clove-Spiced Poultry Aspic",
    "Clove-Spiced Eggs Benedict",
    "Clove-Spiced Creme Brulee",
    "Orange Clove Cheesecake",
    "Clove-Spiced Pear and Cured Meat Flatbread",
    "Clove and Veggie Flatbread",
    "Bowl of Fruit Salad with Orange-Clove Syrup",
    "Spherified Clove-Spiced Oyster Soup",
    "Mashed Purple Potatoes",
    "Bowl of Roasted Lotus Root",
    "Bowl of Cactus Soup",
    "Mango Pie",
    "Bowl of Black Pepper Cactus Salad",
    "Tropical Peppermint Cake",
    "Bowl of Red Lentil Soup",
    "Holographic Super Cake",
    "Plate of Sesame-Crusted Coq Au Vin",
    "Soy-Sesame Sous-Vide Steak",
    "Plate of Clear Truffle and Sesame Ravioli",
    "Plate of Sesame-Ginger Beef Carpaccio",
    "Plate of Sesame Poultry Aspic",
    "Sesame Eggs Benedict",
    "Sesame Creme Brulee",
    "Sesame Cheesecake",
    "Sesame-Asparagus and Cured Meat Flatbread",
    "Sesame Veggie Flatbread",
    "Bowl of Sesame Fruit Salad",
    "Spherified Sesame Oyster Soup",
    "Plate of Coq Au Vin with Mint Garnish",
    "Sous-Vide Steak with Mint-Parsley Sauce",
    "Plate of Clear Truffle and Mint Ravioli",
    "Plate of Beef Carpaccio with Mint Garnish",
    "Plate of Poultry Aspic with Mint Garnish",
    "Eggs Benedict with Mint-Parsley Sauce",
    "Mint Creme Brulee",
    "Mint Strawberry Cheesecake",
    "Mint-Pear Cured Meat Flatbread",
    "Mint and Veggie Flatbread",
    "Bowl of Mists-Infused Fruit Salad with Mint Garnish",
    "Bowl of Fruit Salad with Mint Garnish",
    "Spherified Oyster Soup with Mint Garnish",
    "Indigo Mushroom Milkshake",
    "Slice of Candied Dragon Roll",
    "Omnomberry Pie",
    "Scoop of Mintberry Swirl Ice Cream",
    "Omnomberry Ghost",
    "Winterberry Pie",
    "Slice of Allspice Cake",
    "Slice of Allspice Cake with Ice Cream",
    "Plate of Coq Au Vin with Salsa",
    "Cilantro Lime Sous-Vide Steak",
    "Plate of Clear Truffle and Cilantro Ravioli",
    "Plate of Beef Carpaccio with Salsa Garnish",
    "Plate of Poultry Aspic with Salsa Garnish",
    "Salsa Eggs Benedict",
    "Mango Cilantro Creme Brulee",
    "Strawberry Cilantro Cheesecake",
    "Cilantro and Cured Meat Flatbread",
    "Salsa-Topped Veggie Flatbread",
    "Bowl of Fruit Salad with Cilantro Garnish",
    "Spherified Cilantro Oyster Soup",
    "Bowl of Fire Veggie Chili",
    "Plate of Sugar Rib Roast",
    "Ghost Pepper Popper",
    "Fried Golden Dumpling",
    "Bowl of Prickly Pear Sorbet",
    "Winterberry Sorbet",
    "Plate of Roasted Cactus",
    "Bowl of Orrian Truffle and Meat Stew",
    "Bowl of Marjory's Experimental Chili",
    "Jerk Poultry and Nopal Flatbread Sandwich",
    "Bowl of Tapioca Pudding",
    "Cheesy Cassava Roll",
    "Plate of Mushrooms Yakkington",
    "Bowl of Lotus Stirfry",
    "Egg in a Cloud",
    "Bowl of Truffle Sautee",
    "Omnomberry Compote",
    "Swiftly Scrambled Eggs",
    "Experimental Remnant",
    "Bowl of Seaweed Salad",
    "Bowl of Winterberry Seaweed Salad",
    "Spring Roll",
    "Dragon's Breath Bun",
    "Plate of Truffle Steak Dinner",
    "Carrot Soufflé",
    "Jerk Poultry Flatbread Sandwich",
    "Steamed Red Dumpling",
    "Block of Tofu",
    "Saffron Stuffed Mushroom",
    "Plate of Sweet Curried Mussels",
    "Bowl of Spiced Red Lentil Stew",
    "Icy Fish Snack",
    "Dragonfish Candy",
    "Plate of Lemongrass Poultry",
    "Cup of Light-Roasted Coffee",
    "Bowl of Fire Salsa"
  )

  def ultimateBravery: String = {
    val roll = Math.round(Math.random() * (food.length - 1)).toInt
    food(roll)
  }
}
