package UltimateBravery.src.main.Skills

import UltimateBravery.src.main.ClassSpecific.Classes

class UtilitySkills {

  private val classes = new Classes

  private val warriorSkillsV2: List[Skill] = List(
    new Skill("On Your Knees!",77114, classes.PARAGON),
    new Skill("Brace Yourselves!",76934, classes.PARAGON),
    new Skill("Never Surrender!",76769, classes.PARAGON),
    new Skill("Find Their Weakness!",77040, classes.PARAGON),
    new Skill("Dragonspike Mine",62960, classes.BLADESWORN),
    new Skill("Electric Fence",62804, classes.BLADESWORN),
    new Skill("Overcharged Cartridges",68085, classes.BLADESWORN),
    new Skill("Flow Stabilizer",62967, classes.BLADESWORN),
    new Skill("Break Enchantments",43123, classes.SPELLBREAKER),
    new Skill("Imminent Threat",41919, classes.SPELLBREAKER),
    new Skill("Sight beyond Sight",43745, classes.SPELLBREAKER),
    new Skill("Featherfoot Grace",45380, classes.SPELLBREAKER),
    new Skill("Outrage",30258, classes.BERSERKER),
    new Skill("Sundering Leap",29613, classes.BERSERKER),
    new Skill("Shattering Blow",30074, classes.BERSERKER),
    new Skill("Wild Blow",29941, classes.BERSERKER),
    new Skill("Frenzy",14368, classes.WARRIOR),
    new Skill("Balanced Stance",14412, classes.WARRIOR),
    new Skill("Endure Pain",14392, classes.WARRIOR),
    new Skill("Berserker Stance",14406, classes.WARRIOR),
    new Skill("Banner of Tactics",14408, classes.WARRIOR),
    new Skill("Banner of Discipline",14407, classes.WARRIOR),
    new Skill("Banner of Strength",14405, classes.WARRIOR),
    new Skill("Banner of Defense",14528, classes.WARRIOR),
    new Skill("Fear Me!",14409, classes.WARRIOR),
    new Skill("On My Mark!",14575, classes.WARRIOR),
    new Skill("Shake It Off!",14372, classes.WARRIOR),
    new Skill("For Great Justice!",14403, classes.WARRIOR),
    new Skill("Dolyak Signet",14413, classes.WARRIOR),
    new Skill("Signet of Stamina",14479, classes.WARRIOR),
    new Skill("Signet of Fury",14410, classes.WARRIOR),
    new Skill("Signet of Might",14404, classes.WARRIOR),
    new Skill("Stomp",14388, classes.WARRIOR),
    new Skill("Bull's Charge",14516, classes.WARRIOR),
    new Skill("Throw Bolas",14354, classes.WARRIOR),
    new Skill("Kick",14502, classes.WARRIOR)
  )

  private val warriorSkills:List[(String, String)] = List(
    ("Banner of Defense", classes.WARRIOR),
    ("Banner of Discipline", classes.WARRIOR),
    ("Banner of Strength", classes.WARRIOR),
    ("Banner of Tactics", classes.WARRIOR),
    ("Bull's Charge", classes.WARRIOR),
    ("Kick", classes.WARRIOR),
    ("Stomp", classes.WARRIOR),
    ("Throw Bolas", classes.WARRIOR),
    ("Fear Me!", classes.WARRIOR),
    ("For Great Justice!", classes.WARRIOR),
    ("On My Mark!", classes.WARRIOR),
    ("Shake It Off!", classes.WARRIOR),
    ("Dolyak Signet", classes.WARRIOR),
    ("Signet of Fury", classes.WARRIOR),
    ("Signet of Might", classes.WARRIOR),
    ("Signet of Stamina", classes.WARRIOR),
    ("Balanced Stance", classes.WARRIOR),
    ("Berserker Stance", classes.WARRIOR),
    ("Endure Pain", classes.WARRIOR),
    ("Frenzy", classes.WARRIOR),
    ("Outrage", classes.BERSERKER),
    ("Shattering Blow", classes.BERSERKER),
    ("Sundering Leap", classes.BERSERKER),
    ("Wild Blow", classes.BERSERKER),
    ("Break Enchantments", classes.SPELLBREAKER),
    ("Featherfoot Grace", classes.SPELLBREAKER),
    ("Imminent Threat", classes.SPELLBREAKER),
    ("Sight beyond Sight", classes.SPELLBREAKER),
    ("Dragonspike Mine", classes.BLADESWORN),
    ("Electric Fence", classes.BLADESWORN),
    ("Flow Stabilizer", classes.BLADESWORN),
    ("Overcharged Cartridges", classes.BLADESWORN)
  )

  private val guardianSkillsV2:List[Skill] = List(
    new Skill("Valorous Stance",77300, classes.LUMINARY),
    new Skill("Effulgent Stance",76813, classes.LUMINARY),
    new Skill("Piercing Stance",77078, classes.LUMINARY),
    new Skill("Stalwart Stance",77321, classes.LUMINARY),
    new Skill("Heel Crack",62549, classes.WILLBENDER),
    new Skill("Whirling Light",62565, classes.WILLBENDER),
    new Skill("Roiling Light",62521, classes.WILLBENDER),
    new Skill("Flash Combo",62608, classes.WILLBENDER),
    new Skill("Mantra of Lore",45460, classes.FIREBRAND),
    new Skill("Mantra of Truth",44080, classes.FIREBRAND),
    new Skill("Mantra of Flame",46148, classes.FIREBRAND),
    new Skill("Mantra of Potence",40915, classes.FIREBRAND),
    new Skill("Light's Judgment",30871, classes.DRAGONHUNTER),
    new Skill("Procession of Blades",30364, classes.DRAGONHUNTER),
    new Skill("Fragments of Faith",30553, classes.DRAGONHUNTER),
    new Skill("Test of Faith",29786, classes.DRAGONHUNTER),
    new Skill("Merciful Intervention",9246, classes.GUARDIAN),
    new Skill("Judge's Intervention",9247, classes.GUARDIAN),
    new Skill("Contemplation of Purity",9248, classes.GUARDIAN),
    new Skill("Smite Condition",9245, classes.GUARDIAN),
    new Skill("Sanctuary",9128, classes.GUARDIAN),
    new Skill("Hallowed Ground",9253, classes.GUARDIAN),
    new Skill("Purging Flames",9187, classes.GUARDIAN),
    new Skill("Wall of Reflection",9251, classes.GUARDIAN),
    new Skill("Hold the Line!",9152, classes.GUARDIAN),
    new Skill("Stand Your Ground!",9153, classes.GUARDIAN),
    new Skill("Save Yourselves!",9085, classes.GUARDIAN),
    new Skill("Advance!",9084, classes.GUARDIAN),
    new Skill("Signet of Mercy",9163, classes.GUARDIAN),
    new Skill("Signet of Wrath",9151, classes.GUARDIAN),
    new Skill("Signet of Judgment",9150, classes.GUARDIAN),
    new Skill("Bane Signet",9093, classes.GUARDIAN),
    new Skill("Shield of the Avenger",9182, classes.GUARDIAN),
    new Skill("Bow of Truth",9175, classes.GUARDIAN),
    new Skill("Sword of Justice",9168, classes.GUARDIAN),
    new Skill("Hammer of Wisdom",9125, classes.GUARDIAN)
  )

  private val guardianSkills:List[(String, String)] = List(
    ("Hallowed Ground", classes.GUARDIAN),
    ("Purging Flames", classes.GUARDIAN),
    ("Sanctuary", classes.GUARDIAN),
    ("Wall of Reflection", classes.GUARDIAN),
    ("Contemplation of Purity", classes.GUARDIAN),
    ("Judge's Intervention", classes.GUARDIAN),
    ("Merciful Intervention", classes.GUARDIAN),
    ("Smite Condition", classes.GUARDIAN),
    ("Advance!", classes.GUARDIAN),
    ("Hold the Line!", classes.GUARDIAN),
    ("Save Yourselves!", classes.GUARDIAN),
    ("Stand Your Ground!", classes.GUARDIAN),
    ("Bane Signet", classes.GUARDIAN),
    ("Signet of Judgement", classes.GUARDIAN),
    ("Signet of Mercy", classes.GUARDIAN),
    ("Signet of Wrath", classes.GUARDIAN),
    ("Bow of Truth", classes.GUARDIAN),
    ("Hammer of Wisdom", classes.GUARDIAN),
    ("Shield of the Avenger", classes.GUARDIAN),
    ("Sword of Justice", classes.GUARDIAN),
    ("Fragments of Faith", classes.DRAGONHUNTER),
    ("Light's Judgement", classes.DRAGONHUNTER),
    ("Procession of Blades", classes.DRAGONHUNTER),
    ("Test of Faith", classes.DRAGONHUNTER),
    ("Mantra of Flame", classes.FIREBRAND),
    ("Mantra of Lore", classes.FIREBRAND),
    ("Mantra of Potence", classes.FIREBRAND),
    ("Mantra of Truth", classes.FIREBRAND),
    ("Flash Combo", classes.WILLBENDER),
    ("Heel Crack", classes.WILLBENDER),
    ("Roiling Light", classes.WILLBENDER),
    ("Whirling Light", classes.WILLBENDER)
  )

  private val revenantSkillsV2:List[Skill] = List(
    new Skill("Legendary Assassin Stance", 0, classes.REVENANT),
    new Skill("Legendary Centaur Stance", 0, classes.REVENANT),
    new Skill("Legendary Demon Stance", 0, classes.REVENANT),
    new Skill("Legendary Dwarf Stance", 0, classes.REVENANT),
    new Skill("Legendary Dragon Stance", 0, classes.HERALD),
    new Skill("Legendary Renegade Stance", 0, classes.RENEGADE),
    new Skill("Legendary Alliance Stance", 0, classes.VINDICATOR),
    new Skill("Legendary Entity Stance", 0, classes.CONDUIT)
  )

  private val revenantSkills:List[(String, String)] = List(
    ("Legendary Assassin Stance", classes.REVENANT),
    ("Legendary Centaur Stance", classes.REVENANT),
    ("Legendary Demon Stance", classes.REVENANT),
    ("Legendary Dwarf Stance", classes.REVENANT),
    ("Legendary Dragon Stance", classes.HERALD),
    ("Legendary Renegade Stance", classes.RENEGADE),
    ("Legendary Alliance Stance", classes.VINDICATOR)
  )

  private val engineerSkillsV2:List[Skill] = List(
    new Skill("Plasmatic State",77209, classes.AMALGAM),
    new Skill("Gaseous State",77018, classes.AMALGAM),
    new Skill("Liquid State",76908, classes.AMALGAM),
    new Skill("Solid State",77069, classes.AMALGAM),
    new Skill("Spectrum Shield",41218, classes.HOLOSMITH),
    new Skill("Hard Light Arena",44646, classes.HOLOSMITH),
    new Skill("Laser Disk",42842, classes.HOLOSMITH),
    new Skill("Photon Wall",43739, classes.HOLOSMITH),
    new Skill("Superconducting Signet",63113, classes.MECHANIST),
    new Skill("Force Signet",63253, classes.MECHANIST),
    new Skill("Shift Signet",63111, classes.MECHANIST),
    new Skill("Barrier Signet",63262, classes.MECHANIST),
    new Skill("Shredder Gyro",29921, classes.SCRAPPER),
    new Skill("Blast Gyro",31248, classes.SCRAPPER),
    new Skill("Purge Gyro",29739, classes.SCRAPPER),
    new Skill("Bulwark Gyro",30101, classes.SCRAPPER),
    new Skill("Slick Shoes",5825, classes.ENGINEER),
    new Skill("Personal Battering Ram",5811, classes.ENGINEER),
    new Skill("Rocket Boots",5910, classes.ENGINEER),
    new Skill("Utility Goggles",5865, classes.ENGINEER),
    new Skill("Throw Mine",6161, classes.ENGINEER),
    new Skill("Tool Kit",5904, classes.ENGINEER),
    new Skill("Elixir Gun",5933, classes.ENGINEER),
    new Skill("Flamethrower",5927, classes.ENGINEER),
    new Skill("Bomb Kit",5812, classes.ENGINEER),
    new Skill("Grenade Kit",5805, classes.ENGINEER),
    new Skill("Elixir R",5968, classes.ENGINEER),
    new Skill("Elixir C",5860, classes.ENGINEER),
    new Skill("Elixir S",5861, classes.ENGINEER),
    new Skill("Elixir U",5862, classes.ENGINEER),
    new Skill("Elixir B",5821, classes.ENGINEER),
    new Skill("Rocket Turret",5912, classes.ENGINEER),
    new Skill("Thumper Turret",5838, classes.ENGINEER),
    new Skill("Net Turret",5837, classes.ENGINEER),
    new Skill("Flame Turret",5836, classes.ENGINEER),
    new Skill("Rifle Turret",5818, classes.ENGINEER)
  )

  private val engineerSkills:List[(String, String)] = List(
    ("Elixir B", classes.ENGINEER),
    ("Elixir C", classes.ENGINEER),
    ("Elixir R", classes.ENGINEER),
    ("Elixir S", classes.ENGINEER),
    ("Elixir U", classes.ENGINEER),
    ("Bomb Kit", classes.ENGINEER),
    ("Elixir Gun", classes.ENGINEER),
    ("Flamethrower", classes.ENGINEER),
    ("Grenade Kit", classes.ENGINEER),
    ("Tool Kit", classes.ENGINEER),
    ("Personal Battering Ram", classes.ENGINEER),
    ("Rocket Boots", classes.ENGINEER),
    ("Slick Shoes", classes.ENGINEER),
    ("Throw Mine", classes.ENGINEER),
    ("Utility Googles", classes.ENGINEER),
    ("Rifle turret", classes.ENGINEER),
    ("Flame Turret", classes.ENGINEER),
    ("Harpoon Turret", classes.ENGINEER),
    ("Net Turret", classes.ENGINEER),
    ("Rocket Turret", classes.ENGINEER),
    ("Thumber Turret", classes.ENGINEER),
    ("Blast Gyro", classes.SCRAPPER),
    ("Bulwark Gyro", classes.SCRAPPER),
    ("Purge Gyro", classes.SCRAPPER),
    ("Shredder Gyro", classes.SCRAPPER),
    ("Hard Light Arena", classes.HOLOSMITH),
    ("Laser Disk", classes.HOLOSMITH),
    ("Photon Wall", classes.HOLOSMITH),
    ("Spectrum Shield", classes.HOLOSMITH),
    ("Barrier Signet", classes.MECHANIST),
    ("Force Signet", classes.MECHANIST),
    ("Shift Signet", classes.MECHANIST),
    ("Superconducting Signet", classes.MECHANIST)
  )

  private val thiefSkillsV2:List[Skill] = List(
    new Skill("Emergency Jade Shield",76879, classes.ANTIQUARY),
    new Skill("Canach-Coin Toss",77230, classes.ANTIQUARY),
    new Skill("Inquest Portal Device",76808, classes.ANTIQUARY),
    new Skill("Stone Summit Cannon",76725, classes.ANTIQUARY),
    new Skill("Well of Sorrow",63276, classes.SPECTER),
    new Skill("Well of Silence",63230, classes.SPECTER),
    new Skill("Well of Tears",63294, classes.SPECTER),
    new Skill("Well of Bounty",63323, classes.SPECTER),
    new Skill("Shadow Flare",41158, classes.DEADEYE),
    new Skill("Mercy",41372, classes.DEADEYE),
    new Skill("Binding Shadow",41205, classes.DEADEYE),
    new Skill("Shadow Gust",46335, classes.DEADEYE),
    new Skill("Impairing Daggers",30369, classes.DAREDEVIL),
    new Skill("Bandit's Defense",30661, classes.DAREDEVIL),
    new Skill("Distracting Daggers",30568, classes.DAREDEVIL),
    new Skill("Fist Flurry",30868, classes.DAREDEVIL),
    new Skill("Shadow Refuge",13117, classes.THIEF),
    new Skill("Smoke Screen",13065, classes.THIEF),
    new Skill("Blinding Powder",13044, classes.THIEF),
    new Skill("Shadowstep",13002, classes.THIEF),
    new Skill("Caltrops",13028, classes.THIEF),
    new Skill("Haste",13066, classes.THIEF),
    new Skill("Roll for Initiative",13035, classes.THIEF),
    new Skill("Scorpion Wire",13020, classes.THIEF),
    new Skill("Signet of Shadows",13060, classes.THIEF),
    new Skill("Signet of Agility",13062, classes.THIEF),
    new Skill("Infiltrator's Signet",13064, classes.THIEF),
    new Skill("Assassin's Signet",13046, classes.THIEF),
    new Skill("Prepare Seal Area",13056, classes.THIEF),
    new Skill("Prepare Shadow Portal",13038, classes.THIEF),
    new Skill("Prepare Thousand Needles",13026, classes.THIEF),
    new Skill("Prepare Pitfall",13057, classes.THIEF),
    new Skill("Devourer Venom",13093, classes.THIEF),
    new Skill("Ice Drake Venom",13096, classes.THIEF),
    new Skill("Skale Venom",13055, classes.THIEF),
    new Skill("Spider Venom",13037, classes.THIEF)
  )

  private val thiefSkills:List[(String, String)] = List(
    ("Blinding Powder", classes.THIEF),
    ("Shadow Refuge", classes.THIEF),
    ("Shadowstep", classes.THIEF),
    ("Smoke Screen", classes.THIEF),
    ("Prepare Pitfall", classes.THIEF),
    ("Prepare Seal Area", classes.THIEF),
    ("Prepare Shadow Portal", classes.THIEF),
    ("Prepare Thousand Needles", classes.THIEF),
    ("Assassin's Signet", classes.THIEF),
    ("Infiltrator's Signet", classes.THIEF),
    ("Signet of Agility", classes.THIEF),
    ("Signet of Shadows", classes.THIEF),
    ("Caltrops", classes.THIEF),
    ("Haste", classes.THIEF),
    ("Roll for Initiative", classes.THIEF),
    ("Scorpion Wire", classes.THIEF),
    ("Devourer Venom", classes.THIEF),
    ("Ice Drake Venom", classes.THIEF),
    ("Skale Venom", classes.THIEF),
    ("Spider Venom", classes.THIEF),
    ("Bandit's Defense", classes.DAREDEVIL),
    ("Distracting Daggers", classes.DAREDEVIL),
    ("Fist Flurry", classes.DAREDEVIL),
    ("Impairing Daggers", classes.DAREDEVIL),
    ("Binding Shadow", classes.DEADEYE),
    ("Mercy", classes.DEADEYE),
    ("Shadow Flare", classes.DEADEYE),
    ("Shadow Gust", classes.DEADEYE),
    ("Well of Bounty", classes.SPECTER),
    ("Well of Silence", classes.SPECTER),
    ("Well of Sorrow", classes.SPECTER),
    ("Well of Tears", classes.SPECTER)
  )

  private val rangerSkillsV2:List[Skill] = List(
    new Skill("Mistral",76757, classes.GALESHOT),
    new Skill("Whirlwind",76619, classes.GALESHOT),
    new Skill("Wind Shear",77211, classes.GALESHOT),
    new Skill("Piercing Gales",77264, classes.GALESHOT),
    new Skill("Nature's Binding",63130, classes.UNTAMED),
    new Skill("Unnatural Traversal",63195, classes.UNTAMED),
    new Skill("Mutate Conditions",63256, classes.UNTAMED),
    new Skill("Exploding Spores",63157, classes.UNTAMED),
    new Skill("Vulture Stance",40498, classes.SOULBEAST),
    new Skill("Moa Stance",45970, classes.SOULBEAST),
    new Skill("Griffon Stance",45142, classes.SOULBEAST),
    new Skill("Dolyak Stance",45789, classes.SOULBEAST),
    new Skill("Glyph of the Tides",30238, classes.DRUID),
    new Skill("Glyph of Unity",31582, classes.DRUID),
    new Skill("Glyph of Equality",31746, classes.DRUID),
    new Skill("Glyph of Alignment",31322, classes.DRUID),
    new Skill("Search and Rescue!",34309, classes.RANGER),
    new Skill("Guard!",12632, classes.RANGER),
    new Skill("Protect Me!",12631, classes.RANGER),
    new Skill("Sic 'Em!",12633, classes.RANGER),
    new Skill("Storm Spirit",12493, classes.RANGER),
    new Skill("Frost Spirit",12497, classes.RANGER),
    new Skill("Stone Spirit",12495, classes.RANGER),
    new Skill("Sun Spirit",12498, classes.RANGER),
    new Skill("Quickening Zephyr",12550, classes.RANGER),
    new Skill("Muddy Terrain",12501, classes.RANGER),
    new Skill("Lightning Reflexes",12494, classes.RANGER),
    new Skill("Sharpening Stone",12537, classes.RANGER),
    new Skill("Signet of the Wild",12491, classes.RANGER),
    new Skill("Signet of Stone",12500, classes.RANGER),
    new Skill("Signet of the Hunt",12542, classes.RANGER),
    new Skill("Signet of Renewal",12502, classes.RANGER),
    new Skill("Frost Trap",12492, classes.RANGER),
    new Skill("Viper's Nest",12496, classes.RANGER),
    new Skill("Flame Trap",12499, classes.RANGER),
    new Skill("Spike Trap",12476, classes.RANGER)
  )

  private val rangerSkills:List[(String, String)] = List(
    ("Guard!", classes.RANGER),
    ("Protect Me!", classes.RANGER),
    ("Search and Rescue!", classes.RANGER),
    ("Sic 'Em!", classes.RANGER),
    ("Signet of Renewal", classes.RANGER),
    ("Signet of Stone", classes.RANGER),
    ("Signet of the Hunt", classes.RANGER),
    ("Signet of the Wild", classes.RANGER),
    ("Frost Spirit", classes.RANGER),
    ("Stone Spirit", classes.RANGER),
    ("Storm Spirit", classes.RANGER),
    ("Sun Spirit", classes.RANGER),
    ("Lightning Reflexes", classes.RANGER),
    ("Muddy Terrain", classes.RANGER),
    ("Quickening Zephyr", classes.RANGER),
    ("Sharpening Stone", classes.RANGER),
    ("Flame Trap", classes.RANGER),
    ("Frost Trap", classes.RANGER),
    ("Spike Trap", classes.RANGER),
    ("Viper's Next", classes.RANGER),
    ("Glyph of Alignment", classes.DRUID),
    ("Glyph of Equality", classes.DRUID),
    ("Glyph of Unity", classes.DRUID),
    ("Glyph of the Tides", classes.DRUID),
    ("Dolyak Stance", classes.SOULBEAST),
    ("Griffon Stance", classes.SOULBEAST),
    ("Moa Stance", classes.SOULBEAST),
    ("Vulture Stance", classes.SOULBEAST),
    ("Exploding Spores", classes.UNTAMED),
    ("Mutate Conditions", classes.UNTAMED),
    ("Nature's Binding", classes.UNTAMED),
    ("Unnatural Traversal", classes.UNTAMED)
  )

  private val mesmerSkillsV2:List[Skill] = List(
    new Skill("Tale of the Valiant Marshal",77178, classes.TROUBADOUR),
    new Skill("Tale of the Honorable Rogue",76611, classes.TROUBADOUR),
    new Skill("Tale of the Tortured Mastermind",77066, classes.TROUBADOUR),
    new Skill("Tale of the Soulkeeper",76850, classes.TROUBADOUR),
    new Skill("Sword of Decimation",35637, classes.VIRTUOSO),
    new Skill("Blade Renewal",43343, classes.VIRTUOSO),
    new Skill("Rain of Swords",45425, classes.VIRTUOSO),
    new Skill("Psychic Force",62573, classes.VIRTUOSO),
    new Skill("Crystal Sands",41065, classes.MIRAGE),
    new Skill("Sand through Glass",43064, classes.MIRAGE),
    new Skill("Mirage Advance",42851, classes.MIRAGE),
    new Skill("Illusionary Ambush",45046, classes.MIRAGE),
    new Skill("Well of Action",30814, classes.CHRONOMANCER),
    new Skill("Well of Senility",29856, classes.CHRONOMANCER),
    new Skill("Well of Calamity",30525, classes.CHRONOMANCER),
    new Skill("Well of Precognition",29526, classes.CHRONOMANCER),
    new Skill("Veil",10187, classes.MESMER),
    new Skill("Portal Entre",10197, classes.MESMER),
    new Skill("Feedback",10302, classes.MESMER),
    new Skill("Null Field",10203, classes.MESMER),
    new Skill("Phantasmal Disenchanter",10267, classes.MESMER),
    new Skill("Phantasmal Defender",10341, classes.MESMER),
    new Skill("Mirror Images",10202, classes.MESMER),
    new Skill("Decoy",10201, classes.MESMER),
    new Skill("Mimic",29578, classes.MESMER),
    new Skill("Illusion of Life",10244, classes.MESMER),
    new Skill("Arcane Thievery",10185, classes.MESMER),
    new Skill("Blink",10200, classes.MESMER),
    new Skill("Mantra of Concentration",10237, classes.MESMER),
    new Skill("Mantra of Resolve",10207, classes.MESMER),
    new Skill("Mantra of Distraction",10204, classes.MESMER),
    new Skill("Mantra of Pain",10211, classes.MESMER),
    new Skill("Signet of Illusions",10247, classes.MESMER),
    new Skill("Signet of Midnight",10234, classes.MESMER),
    new Skill("Signet of Domination",10232, classes.MESMER),
    new Skill("Signet of Inspiration",10236, classes.MESMER)
  )

  private val mesmerSkills:List[(String, String)] = List(
    ("Decoy", classes.MESMER),
    ("Mirror Images", classes.MESMER),
    ("Feedback", classes.MESMER),
    ("Null Field", classes.MESMER),
    ("Portal Entre", classes.MESMER),
    ("Veil", classes.MESMER),
    ("Arcane Thievery", classes.MESMER),
    ("Blink", classes.MESMER),
    ("Illusion of Life", classes.MESMER),
    ("Mimic", classes.MESMER),
    ("Mantra of Concentration", classes.MESMER),
    ("Mantra of Distraction", classes.MESMER),
    ("Mantra of Pain", classes.MESMER),
    ("Mantra of Resolve", classes.MESMER),
    ("Phantasmal Defender", classes.MESMER),
    ("Phantasmal Disenchanter", classes.MESMER),
    ("Signet of Domination", classes.MESMER),
    ("Signet of Illusions", classes.MESMER),
    ("Signet of Inspiration", classes.MESMER),
    ("Signet of Midnight", classes.MESMER),
    ("Well of Action", classes.CHRONOMANCER),
    ("Well of Calamity", classes.CHRONOMANCER),
    ("Well of Precognition", classes.CHRONOMANCER),
    ("Well of Senility", classes.CHRONOMANCER),
    ("Crystal Sands", classes.MIRAGE),
    ("Illusionary Ambush", classes.MIRAGE),
    ("Mirage Advance", classes.MIRAGE),
    ("Sand through Glass", classes.MIRAGE),
    ("Blade Renewal", classes.VIRTUOSO),
    ("Psychic Force", classes.VIRTUOSO),
    ("Rain of Swords", classes.VIRTUOSO),
    ("Sword of Decimation", classes.VIRTUOSO)
  )

  private val necromancerSkillsV2:List[Skill] = List(
    new Skill("Weapon of Warding",76752, classes.RITUALIST),
    new Skill("Nightmare Weapon",76739, classes.RITUALIST),
    new Skill("Weapon of Remedy",77022, classes.RITUALIST),
    new Skill("Splinter Weapon",76975, classes.RITUALIST),
    new Skill("Elixir of Anguish",62662, classes.HARBINGER),
    new Skill("Elixir of Bliss",62514, classes.HARBINGER),
    new Skill("Elixir of Ignorance",62646, classes.HARBINGER),
    new Skill("Elixir of Risk",62530, classes.HARBINGER),
    new Skill("Serpent Siphon",41615, classes.SCOURGE),
    new Skill("Sand Swell",42917, classes.SCOURGE),
    new Skill("Desiccate",42935, classes.SCOURGE),
    new Skill("Trail of Anguish",40274, classes.SCOURGE),
    new Skill("Rise!",30772, classes.REAPER),
    new Skill("Nothing Can Save You!",29666, classes.REAPER),
    new Skill("Suffer!",30670, classes.REAPER),
    new Skill("You Are All Weaklings!",29414, classes.REAPER),
    new Skill("Blood Is Power",10544, classes.NECROMANCER),
    new Skill("Corrupt Boon",10602, classes.NECROMANCER),
    new Skill("Epidemic",10606, classes.NECROMANCER),
    new Skill("Corrosive Poison Cloud",10689, classes.NECROMANCER),
    new Skill("Spectral Walk",10685, classes.NECROMANCER),
    new Skill("Spectral Ring",10608, classes.NECROMANCER),
    new Skill("Spectral Grasp",10620, classes.NECROMANCER),
    new Skill("Spectral Armor",10583, classes.NECROMANCER),
    new Skill("Signet of Undeath",10611, classes.NECROMANCER),
    new Skill("Plague Signet",10562, classes.NECROMANCER),
    new Skill("Signet of the Locust",10612, classes.NECROMANCER),
    new Skill("Signet of Spite",10622, classes.NECROMANCER),
    new Skill("Summon Flesh Wurm",10543, classes.NECROMANCER),
    new Skill("Summon Shadow Fiend",10589, classes.NECROMANCER),
    new Skill("Summon Bone Fiend",10533, classes.NECROMANCER),
    new Skill("Summon Bone Minions",10541, classes.NECROMANCER),
    new Skill("Well of Darkness",10607, classes.NECROMANCER),
    new Skill("Well of Power",10609, classes.NECROMANCER),
    new Skill("Well of Corruption",10545, classes.NECROMANCER),
    new Skill("Well of Suffering",10546, classes.NECROMANCER)
  )

  private val necromancerSkills:List[(String, String)] = List(
    ("Blood is Power", classes.NECROMANCER),
    ("Corrosive Poison Cloud", classes.NECROMANCER),
    ("Corrupt Boon", classes.NECROMANCER),
    ("Epidemic", classes.NECROMANCER),
    ("Summon Bone Fiend", classes.NECROMANCER),
    ("Summon Bone Minions", classes.NECROMANCER),
    ("Summon Flesh Wurm", classes.NECROMANCER),
    ("Summon Shadow Fiend", classes.NECROMANCER),
    ("Plague Signet", classes.NECROMANCER),
    ("Signet of Spite", classes.NECROMANCER),
    ("Signet of Undeath", classes.NECROMANCER),
    ("Signet of the Locust", classes.NECROMANCER),
    ("Spectral Armor", classes.NECROMANCER),
    ("Spectral Grasp", classes.NECROMANCER),
    ("Spectral Ring", classes.NECROMANCER),
    ("Spectral Walk", classes.NECROMANCER),
    ("Well of Corruption", classes.NECROMANCER),
    ("Well of Darkness", classes.NECROMANCER),
    ("Well of Power", classes.NECROMANCER),
    ("Well of Suffering", classes.NECROMANCER),
    ("Nothing Can Save You!", classes.REAPER),
    ("Rise!", classes.REAPER),
    ("Suffer!", classes.REAPER),
    ("You Are All Weaklings!", classes.REAPER),
    ("Desiccate", classes.SCOURGE),
    ("Sand Swell", classes.SCOURGE),
    ("Serpent Siphon", classes.SCOURGE),
    ("Trail of Anguish", classes.SCOURGE),
    ("Elixir of Anguish", classes.HARBINGER),
    ("Elixir of Bliss", classes.HARBINGER),
    ("Elixir of Ignorance", classes.HARBINGER),
    ("Elixir of Risk", classes.HARBINGER),
  )

  private val elementalistSkillsV2:List[Skill] = List(
    new Skill("Toad's Fortitude",77320, classes.EVOKER),
    new Skill("Hare's Agility",77038, classes.EVOKER),
    new Skill("Otter's Compassion",77190, classes.BLACK),
    new Skill("Fox's Fury",76711, classes.EVOKER),
    new Skill("Fortified Earth",62826, classes.CATALYST),
    new Skill("Invigorating Air",62982, classes.CATALYST),
    new Skill("Shattering Ice",62698, classes.CATALYST),
    new Skill("Relentless Fire",62965, classes.CATALYST),
    new Skill("Primordial Stance",40183, classes.WEAVER),
    new Skill("Twist of Fate",45746, classes.WEAVER),
    new Skill("Unravel",44612, classes.WEAVER),
    new Skill("Stone Resonance",44926, classes.WEAVER),
    new Skill("Aftershock!",30432, classes.TEMPEST),
    new Skill("Eye of the Storm!",30047, classes.TEMPEST),
    new Skill("Flash-Freeze!",29948, classes.TEMPEST),
    new Skill("Feel the Burn!",30662, classes.TEMPEST),
    new Skill("Conjure Earth Shield",5546, classes.ELEMENTALIST),
    new Skill("Conjure Lightning Hammer",5624, classes.ELEMENTALIST),
    new Skill("Conjure Frost Bow",5567, classes.ELEMENTALIST),
    new Skill("Conjure Flame Axe",5540, classes.ELEMENTALIST),
    new Skill("Armor of Earth",5639, classes.ELEMENTALIST),
    new Skill("Lightning Flash",5536, classes.ELEMENTALIST),
    new Skill("Mist Form",5554, classes.ELEMENTALIST),
    new Skill("Cleansing Fire",5535, classes.ELEMENTALIST),
    new Skill("Signet of Earth",5571, classes.ELEMENTALIST),
    new Skill("Signet of Air",5572, classes.ELEMENTALIST),
    new Skill("Signet of Water",5570, classes.ELEMENTALIST),
    new Skill("Signet of Fire",5542, classes.ELEMENTALIST),
    new Skill("Glyph of Renewal",5573, classes.ELEMENTALIST),
    new Skill("Glyph of Lesser Elementals",5502, classes.ELEMENTALIST),
    new Skill("Glyph of Storms",5734, classes.ELEMENTALIST),
    new Skill("Glyph of Elemental Power",5506, classes.ELEMENTALIST),
    new Skill("Arcane Blast",5539, classes.ELEMENTALIST),
    new Skill("Arcane Echo",5635, classes.ELEMENTALIST),
    new Skill("Arcane Shield",5641, classes.ELEMENTALIST),
    new Skill("Arcane Wave",5638, classes.ELEMENTALIST)
  )

  private val elementalistSkills:List[(String, String)] = List(
    ("Arcane Blast", classes.ELEMENTALIST),
    ("Arcane Power", classes.ELEMENTALIST),
    ("Arcane Shield", classes.ELEMENTALIST),
    ("Arcane Wave", classes.ELEMENTALIST),
    ("Armor of Earth", classes.ELEMENTALIST),
    ("Cleansing Fire", classes.ELEMENTALIST),
    ("Lightning Flash", classes.ELEMENTALIST),
    ("Mist Form", classes.ELEMENTALIST),
    ("Conjure Earth Shield", classes.ELEMENTALIST),
    ("Conjure Flame Axe", classes.ELEMENTALIST),
    ("Conjure Frost Bow", classes.ELEMENTALIST),
    ("Conjure Lightning Hammer", classes.ELEMENTALIST),
    ("Glyph of Elemental Power", classes.ELEMENTALIST),
    ("Glyph of Lesser Elementals", classes.ELEMENTALIST),
    ("Glyph of Renewal", classes.ELEMENTALIST),
    ("Glyph of Storms", classes.ELEMENTALIST),
    ("Signet of Air", classes.ELEMENTALIST),
    ("Signet of Earth", classes.ELEMENTALIST),
    ("Signet of Fire", classes.ELEMENTALIST),
    ("Signet of Water", classes.ELEMENTALIST),
    ("Aftershock!", classes.TEMPEST),
    ("Eye of the Storm!", classes.TEMPEST),
    ("Feel the Burn!", classes.TEMPEST),
    ("Flash-Freeze!", classes.TEMPEST),
    ("Primordial Stance", classes.WEAVER),
    ("Stone Resonance", classes.WEAVER),
    ("Twist of Fate", classes.WEAVER),
    ("Unravel", classes.WEAVER),
    ("Fortified Earth", classes.CATALYST),
    ("Invigorating Air", classes.CATALYST),
    ("Relentless Fire", classes.CATALYST),
    ("Shattering Ice", classes.CATALYST),
  )

  private val skillLists: List[(List[(String, String)], String)] = List(
    (warriorSkills, classes.WARRIOR),
    (guardianSkills, classes.GUARDIAN),
    (revenantSkills, classes.REVENANT),
    (engineerSkills, classes.ENGINEER),
    (rangerSkills, classes.RANGER),
    (thiefSkills, classes.THIEF),
    (mesmerSkills, classes.MESMER),
    (necromancerSkills, classes.NECROMANCER),
    (elementalistSkills, classes.ELEMENTALIST)
  )

  def ultimateBravery(classRoll: String): String = {
    val baseClass = classes.getBaseClass(classRoll)
    val skillList = filterSkills(getSkillList(baseClass), baseClass, classRoll)
    if (skillList.isEmpty) "error"
    else {
      val roll = Math.round(Math.random() * (skillList.length - 1)).toInt
      skillList(roll)._1
    }
  }

  private def filterSkills(skillList: List[(String, String)], baseClass: String, eliteSpec: String): List[(String, String)] = {
    var newList: List[(String, String)] = List()
    for (skill <- skillList) {
      if (skill._2 == baseClass || skill._2 == eliteSpec) newList = skill :: newList
    }
    newList
  }

  private def getSkillList(baseClass: String): List[(String, String)] = {
    for (skillList <- skillLists) {
      if (skillList._2 == baseClass) return skillList._1
    }
    List()
  }
}
