package UltimateBravery.src.main.Gear.Collections

class Runes {
  val name = "Superior Rune of "
  val runes: List[String] = List(
    "Fireworks",
    "Surging",
    "the Pack",
    "the Citadel",
    "Strength",
    "Privateer",
    "Hoelbrak",
    "the Fire",
    "the Centaur",
    "the Mad King",
    "the Flame Legion",
    "the Baelfire",
    "the Elementalist",
    "the Scholar",
    "the Deadeye",
    "the Ogre",
    "Infiltration",
    "the Spellbreaker",
    "the Mesmer",
    "the Chronomancer",
    "the Reaper",
    "the Daredevil",
    "the Scrapper",
    "the Brawler",
    "the Cavalier",
    "Vampirism",
    "the Holosmith",
    "Lyssa",
    "Rata Sum",
    "the Thief",
    "the Eagle",
    "the Ranger",
    "the Herald",
    "Durability",
    "the Earth",
    "Svanir",
    "the Forgeman",
    "the Engineer",
    "Melandru",
    "the Dolyak",
    "Mercy",
    "the Defender",
    "the Guardian",
    "Resistance",
    "Snowfall",
    "Sanctuary",
    "Radiance",
    "Speed",
    "the Lich",
    "the Ice",
    "the Wurm",
    "the Warrior",
    "the Trooper",
    "Excuberance",
    "the Aristocracy",
    "the Firebrand",
    "the Trapper",
    "the Nightmare",
    "the Krait",
    "Balthazar",
    "Grenth",
    "Perplexity",
    "Thorns",
    "the Afflicted",
    "Tormenting",
    "the Renegade",
    "the Berserker",
    "the Soulbeast",
    "the Adventurer",
    "the Undead",
    "the Mirage",
    "the Necromancer",
    "Scavenging",
    "Antitoxin",
    "the Sunless",
    "Orr",
    "Rage",
    "the Air",
    "Evasion",
    "the Dragonhunter",
    "the Golemancer",
    "the Rebirth",
    "Altruism",
    "the Monk",
    "the Water",
    "the Grove",
    "Dwayna",
    "the Scourge",
    "the Druid",
    "the Flock",
    "Nature's Bounty",
    "the Traveler",
    "Leadership",
    "the Tempest",
    "the Weaver",
    "Divinity",
    "the Revenant",
    "the Zephyrite",
    "the Stars"
  )

  def ultimateBravery: String = {
    val roll = Math.round(Math.random() * (runes.size - 1)).toInt
    name.concat(runes(roll))
  }

}
